In [319]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, cross_val_score, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier


In [ ]:
# Hackerrank input
inp = input()
n, m = tuple([int(x) for x in inp.strip().split(" ")])

df = pd.DataFrame()
X_train = []
y_train = []
for i in range(n):
    inp = input()
    details = inp.split(" ")
    others = details[2:]
    y_train.append(int(details[1]))
    X_train.append([float(x.strip().split(":")[1]) for x in details[2:]])

X_train = np.array(X_train)
y_train = [1 if x > 0 else 0 for x in y_train]

inp = input()
n_test = int(inp)

X_test = []
labels = []

test_df = pd.DataFrame()
for i in range(n_test):
    inp = input()
    details = inp.split(" ")
    labels.append(details[0])
    X_test.append([float(x.strip().split(":")[1]) for x in details[1:]])

X_test = np.array(X_test)
X_test

In [293]:
# Local input
f = open("input.txt", "r")
inp = f.readlines(1)[0]
n, m = tuple([int(x) for x in inp.strip().split(" ")])

df = pd.DataFrame()
X_train = []
y_train = []
for i in range(n):
    inp = f.readlines(1)[0]
    details = inp.split(" ")
    others = details[2:]
    y_train.append(int(details[1]))
    X_train.append([float(x.strip().split(":")[1]) for x in details[2:]])

X_train = np.array(X_train)
y_train = [1 if x > 0 else 0 for x in y_train]

inp = f.readlines(1)[0]
n_test = int(inp)

X_test = []
labels = []

test_df = pd.DataFrame()
for i in range(n_test):
    inp = f.readlines(1)[0]
    details = inp.split(" ")
    labels.append(details[0])
    X_test.append([float(x.strip().split(":")[1]) for x in details[1:]])

X_test = np.array(X_test)
X_test

array([[4.39144628e+10, 1.84751100e+00, 1.00000000e+00, ...,
        4.90527500e+00, 0.00000000e+00, 0.00000000e+00],
       [3.97593881e+11, 0.00000000e+00, 1.00000000e+00, ...,
        2.83321300e+00, 0.00000000e+00, 0.00000000e+00],
       [6.13519705e+10, 0.00000000e+00, 1.00000000e+00, ...,
        2.07944200e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.95858437e+12, 1.87247500e+00, 1.00000000e+00, ...,
        3.40119700e+00, 0.00000000e+00, 0.00000000e+00],
       [5.80257742e+11, 1.31275600e+00, 1.00000000e+00, ...,
        1.79175900e+00, 0.00000000e+00, 0.00000000e+00],
       [6.12324862e+09, 0.00000000e+00, 1.00000000e+00, ...,
        2.48490700e+00, 0.00000000e+00, 0.00000000e+00]])

In [351]:
sg_clf = Pipeline([
    ('std', StandardScaler()),
    ('sgd', SGDClassifier(loss='modified_huber', penalty = 'l2', alpha = 0.1, learning_rate = 'optimal', max_iter = 500, random_state = 42))
])

sg_clf.fit(X_train, y_train)
sg_clf.score(X_train, y_train), cross_val_score(sg_clf, X_train, y_train, cv = 5)

(0.8204444444444444,
 array([0.82444444, 0.80222222, 0.82111111, 0.82111111, 0.81777778]))

In [349]:
%%time
parameters = {'sgd__loss': ['hinge', 'log', 'modified_huber'],
             'sgd__penalty': ['l1','l2','elasticnet'],
             'sgd__alpha': [0.0001, 0.01, 0.1, 1],
              'sgd__learning_rate': ['optimal', 'adaptive'],
              'sgd__eta0': [0.001, 0.01, 0.1, 1]
             }

gs = GridSearchCV(sg_clf, parameters, cv=5)
gs.fit(X_train, y_train)
gs.best_score_, gs.best_params_

Wall time: 35.3 s


(0.8215555555555556,
 {'sgd__alpha': 0.0001,
  'sgd__eta0': 0.001,
  'sgd__learning_rate': 'adaptive',
  'sgd__loss': 'hinge',
  'sgd__penalty': 'l1'})

In [343]:
rf_clf = Pipeline([
    ('std', StandardScaler()),
    ('rf', RandomForestClassifier(n_estimators = 50,
                                  max_depth = 100,
                                  min_samples_split = 2,
                                  min_samples_leaf = 1,
                                  random_state = 42))
])

rf_clf.fit(X_train, y_train)
rf_clf.score(X_train, y_train), cross_val_score(rf_clf, X_train, y_train, cv = 5)

(0.9997777777777778,
 array([0.84777778, 0.84333333, 0.84555556, 0.85      , 0.84777778]))

In [350]:
%%time
parameters = {'rf__n_estimators':[10, 50, 100, 200, 300],
             'rf__max_depth': [5, 10, 50, 100, 200],
             'rf__min_samples_split':[2, 5, 10, 50, 100],
             'rf__min_samples_leaf': [1, 5, 10, 50, 100]}

rs = RandomizedSearchCV(rf_clf, parameters, cv = 5)
rs.fit(X_train, y_train)
rs.best_score_, rs.best_params_

Wall time: 17.7 s


(0.8508888888888889,
 {'rf__n_estimators': 50,
  'rf__min_samples_split': 50,
  'rf__min_samples_leaf': 1,
  'rf__max_depth': 100})

In [277]:
results = np.where(sg_clf.predict(X_test) > 0, 1, -1)
for label, result in zip(labels, results):
    print("{:s} {:+d}".format(label, result))

3rCWr +1
snInN -1
ibfT7 -1
IcbKR +1
SIXmF +1
dLCdh +1
ziFJ8 -1
1WtTD -1
9uIKh +1
df4Mc -1
3nxpY -1
aesmq +1
MyTDz +1
TDMhx +1
Y0rW3 +1
KCcKf +1
2cz5M -1
kqIJj +1
C1Sg2 +1
VAmIt -1
ku9j1 -1
TjHRV +1
sq8Xj -1
uKzm4 -1
3at4H +1
8nXGS -1
4x8ij +1
PeMnA -1
UUPpU -1
HQ4lZ +1
lEv01 +1
XCY52 +1
FNoY7 +1
JJbco -1
PHQ7z -1
Xejsj +1
A4IsT -1
7cU9R -1
8mSRL +1
jRMuo +1
dljxu +1
wZyoj -1
us2ca +1
EVenw -1
QLseT +1
lanI5 +1
RF9di +1
3e6Aa -1
W5mvO -1
LkKbu -1
gbus8 -1
LN4W4 -1
9FNA4 +1
rd3qM +1
pV8eI -1
5wnO7 +1
03KFY -1
i25BS +1
AziH8 +1
YyCpz -1
qLfPb +1
CJBeL +1
EaAPx +1
sQDFf -1
CELfn -1
Ac6Hy -1
ULryN -1
qCBAx +1
Hoz2c -1
8kLbb -1
KAWwb +1
lNMTe +1
MzTHU -1
Sq8XV -1
s8ZUG -1
lDcDx +1
xZoGD +1
vHLAR +1
Ag2kt +1
baqkE -1
Hsbs2 -1
BlvEz -1
CJqsS -1
vbzII +1
R16fw -1
IxBjS +1
yJl2b -1
RXdcX +1
T7uzV -1
ccZGw -1
f9xFZ -1
dO9iE -1
2TaN2 -1
a1XoY -1
1xXiG +1
a8kZK +1
mXe41 +1
8NfbF +1
Sqdti +1
gnCsH -1
YGNBE +1
zOA3j +1
b3Cm5 +1
Wjo2X +1
IcuwU +1
FyieE +1
5OUK8 +1
SjCvq +1
kKVUa +1
CEVSg +1
F2MAp -1
h